### ISSUE TITLE
traceback on all queries

### ISSUE THREAD

**Issue by wryfi** [malnick/logasaurous#1]
Every query I attempt with loga ends in the same traceback:

```
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
main.query(0x7fff5fbffb40, 0xc, 0xc8200634a0, 0x5, 0xa, 0xc8200d2a30, 0x9, 0xc8200d2a50, 0x4, 0xc8200d2a80, ...)
    /Users/chaumes/go/src/github.com/malnick/logasaurus/loga.go:248 +0x24a5
main.main()
    /Users/chaumes/go/src/github.com/malnick/logasaurus/loga.go:341 +0x2434

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 22 [IO wait]:
net.runtime_pollWait(0x6b29c0, 0x72, 0xc8200600b0)
    /usr/local/Cellar/go/1.5.2/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200994f0, 0x72, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200994f0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820099490, 0xc8200dc000, 0x1000, 0x1000, 0x0, 0x6ad028, 0xc8200600b0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820084140, 0xc8200dc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x6b2a80, 0xc820084140, 0xc8200d6108, 0xc8200dc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82008d340, 0xc8200dc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82008b140)
    /usr/local/Cellar/go/1.5.2/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82008b140, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200d60b0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:685 +0xc78

goroutine 23 [select]:
net/http.(*persistConn).writeLoop(0xc8200d60b0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:686 +0xc9d
```

This is on Mac OS X, built with golang-1.5.2 installed via homebrew.

My config.yml:

```

---
# Defined services
define:
  my_example_service: some_value AND another_value
  another_example_service: docker AND haproxy
# Sync time in seconds
sync_interval: 5
sync_depth: 10
# Elasticsearch query configuration
elasticsearch_url: localhost
elasticsearch_port: 9200
# Not actually using this atm
elasticsearch_index: logstash-\*
```

Some example commands that I tried:

```
loga -d "@source_host:'elasticsearch-101'"
loga -d '@source_host:"elasticsearch-101"'
loga -d "elasticsearch-101"
loga -d "syslog_program:apache2"
```

Am I misunderstanding something, or is there something wrong here?
